name: 'Release App'

on:
  push:
    branches:
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            rust_target: aarch64-unknown-linux-gnu
          - os: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc


    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Output info
        run: echo ${{ matrix.platform.os }} ${{ matrix.platform.rust_target }}

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 'Setup Rust'
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          profile: minimal
          toolchain: stable
          target: ${{ matrix.platform.rust_target }}
          
      - uses: Swatinem/rust-cache@v2

      - name: install dependencies (ubuntu x86_64)
        if: matrix.platform.os == 'ubuntu-latest' && matrix.platform.rust_target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
          
      - name: install dependencies (ubuntu aarch64)
        if: matrix.platform.os == 'ubuntu-latest' && matrix.platform.rust_target == 'aarch64-unknown-linux-gnu'
        run: |
          dpkg --add-architecture arm64
          apt update && apt upgrade -y
          apt install -y --no-install-recommends \
                   g++-aarch64-linux-gnu \
                   libc6-dev-arm64-cross \
                   libssl-dev:arm64 \
                   libwebkit2gtk-4.0-dev:arm64 \
                   build-essential \
                   curl:arm64 \
                   wget:arm64 \
                   libgtk-3-dev:arm64 \
                   patchelf:arm64 \
                   librsvg2-dev:arm64 \
                   pkg-config
                   
      - name: Set env vars for aarch64 cross compilation
        if: matrix.platform.os == 'ubuntu-latest' && matrix.platform.rust_target == 'aarch64-unknown-linux-gnu'
        run: | 
          env CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          env CC_aarch64-unknown-linux-gnu=aarch64-linux-gnu-gcc
          env CXX_aarch64-unknown-linux-gnu=aarch64-linux-gnu-g++
          env PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
          env PKG_CONFIG_ALLOW_CROSS=1
          
      - name: Sets env var for params for arm linux compilation
        if: matrix.platform.os == 'ubuntu-latest' && matrix.platform.rust_target != 'x86_64-unknown-linux-gnu'
        run: |
          echo "TAURI_PARAMS='-b deb'" >> $GITHUB_ENV
        
      - name: Build Frontend
        run: yarn && yarn generate

      - uses: JonasKruckenberg/tauri-build@v1.2.2
        id: tauri_build
        with:
          target: ${{ matrix.platform.rust_target }}
          args: ${{ env.TAURI_PARAMS }}

      # The `artifacts` output can now be used by a different action to upload the artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}"

  publish:
    needs: build-binaries
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
      # Download the previously uploaded artifacts
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: artifacts
          path: artifacts
      # And create a release with the artifacts attached
      - name: 'create release'
        uses: softprops/action-gh-release@master
        id: release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          name: "Kanri vx.x.x"
          draft: true
          files: ./artifacts/**/*
          
  
