name: 'Release App'

on:
  push:
    branches:
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        arch: [arm, noarm]
        include:
          - platform: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
            arch: noarm
          - platform: macos-latest
            rust_target: x86_64-apple-darwin
            arch: noarm
          - platform: macos-latest
            rust_target: aarch64-apple-darwin
            arch: arm
          - platform: windows-latest
            rust_target: x86_64-pc-windows-msvc
            arch: noarm
        exclude:
          - platform: windows-latest
            arch: arm
          - platform: ubuntu-latest
            arch: arm

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Output info
        run: echo ${{ matrix.platform}} ${{ matrix.rust_target }} ${{ matrix.arch }}
      
      - name: ensure correct arch for Rust (macos)
        if: matrix.platform == 'macos-latest' && matrix.rust_target == 'aarch64-apple-darwin' && matrix.arch == 'arm'
        run: rustup target add aarch64-apple-darwin && rustup toolchain install stable-aarch64-apple-darwin

      - name: install dependencies (ubuntu x86_64)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
          
      - name: Build Frontend
        run: yarn && yarn generate

      - uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build
        with:
          target: ${{ matrix.rust_target }}

      # The `artifacts` output can now be used by a different action to upload the artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}"

  publish:
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Download the previously uploaded artifacts
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: artifacts
          path: artifacts
      # And create a release with the artifacts attached
      - name: 'create release'
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          draft: true
          files: ./artifacts/**/*
          
  publish-kanri-arm:
      needs: publish
      strategy:
        matrix:
          arch: [arm64, armv7]

      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Install dependencies
          run: yarn install
        - name: Build for ${{ matrix.arch }}
          run: yarn run init:${{matrix.arch}} && yarn run build:${{matrix.arch}}

        - name: Upload Multiple Release Assets
          uses: NBTX/upload-release-assets@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.publish-kanri-common.outputs.upload_url }}
            targets: ./src-tauri/target/*/release/bundle/deb/*.deb
