name: "Release"
on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish-kanri-common:
    if: ${{ false }}  # disable for now
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: Install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    
    - name: Install app dependencies
      run: yarn install
    - name: Build app
      run: yarn generate
    
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
  
  publish-kanri-arm:
    strategy:
      matrix:
        arch: [arm64, armv7]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build for ${{ matrix.arch }}
        run: yarn run init:${{matrix.arch}} && yarn run build:${{matrix.arch}}
      - run: ls -la src-tauri/target/release/bundle/deb
      
